source "https://rubygems.org"

gem "jekyll"
gem "jekyll-include-cache"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "csv"
gem "bigdecimal"
gem "webrick"
